# Choose an optional name for the datacenter.
global:
  datacenter: minidc

# Enable the Consul Web UI via a NodePort.
ui:
  service:
    type: 'NodePort'

# Enable Connect for secure communication between nodes.
connectInject:
  enabled: true
  default: true
# Configure settings for automatic metrics collection.
# These settings are new in Consul 1.5.0.
  centralConfig:
    enabled: true
    defaultProtocol: http
    proxyDefaults: |
      {
      "envoy_dogstatsd_url": "udp://127.0.0.1:9125"
      }

# Enabble gRPC for connect, and monitoring on consul clients themselves.
client:
  enabled: true
  grpc: true
  monitoring:
    enabled: true

# Use only one Consul server for local development.
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
# Enable monitoring on Consul servers themselves.
monitoring:
  enabled: true
